import type {Metadata} from "next";
import {Noto_Sans} from "next/font/google"
import {GeistMono} from 'geist/font/mono';
import "./globals.css";
import {Providers} from "@/components/providers/providers";
import React from "react";
import {NextIntlClientProvider} from "next-intl";
import {getLocale, getMessages} from "next-intl/server";

const notoSans = Noto_Sans({
    subsets: ["latin"],
    display: 'swap',
    variable: '--font-noto-sans',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning
              className={`${notoSans.variable} ${GeistMono.variable} antialiased`}>
        <body>
        <NextIntlClientProvider messages={messages}>
            <Providers>
                {children}
            </Providers>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
