import type { Metadata } from "next";
import {Noto_Sans} from "next/font/google"
import {GeistMono} from 'geist/font/mono';
import "./globals.css";
import {Providers} from "@/components/providers";

const notoSans = Noto_Sans({
    subsets: ["latin"],
    display: 'swap',
    variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${notoSans.variable} ${GeistMono.variable} antialiased`}>
      <body>
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
